# Generated by Django 3.2.5 on 2021-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_auto_20210718_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboard',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
