# Generated by Django 3.2.5 on 2021-07-18 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bulletin_board', '0005_auto_20210718_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bboard',
            name='created_at',
        ),
    ]
