# Generated by Django 3.2.5 on 2021-07-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bulletin_board', '0006_remove_bboard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboard',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bboard',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bulletin_board.rubric',
                                    verbose_name='Рубрика'),
        ),
    ]
